### ISSUE TITLE
Alive ?

### ISSUE THREAD

**Issue by cybernot** [daishisystems/Daishi.Armor.WebFramework#1]
We are considering using this for CSRF protection for a cloud project. I was wondering if the project is well and alive ? there does not seem to be a lot of action on GIT...

**Comment by daishisystems** [comment]
Hi, Apologies for the delay, I'm currently on vacation with limited access
to email. The project is very much alive and well. The first iteration
finished late last year, which contains a fully tested implementation. Our
white-hat guys have been unable to break ARMOR. Since then, we've
implemented the Armor.WebFramework, which provides an easy to implement API
to leverage the core ARMOR code base.
In terms of protecting against CSRF attacks, the core implementation is
complete, and working.
Thanks for considering ARMOR. We're happy to provide direct support should
you go ahead with an implementation. You can contact me directly at
paul at daishisystems dot com
Looking forward to hearing from you.

**Comment by daishisystems** [comment]
Hi, did you go with ARMOR in the end?

**Comment by cybernot** [comment]
We (security team) tried it and like it but we need to work with the
developers to do a PoC/Sample and integrate it in one of our real service.
One we have something working we'll see if we can use it as part of our
best practices.

**Comment by cybernot** [comment]
One consideration for us is that a majority of what we have to cover is .Net 4.0.  That said, we have to weigh the cost of retrofitting Armor back to 4.0 vs. waiting until the various project teams decide to move their projects to 4.5 or beyond.
